### ISSUE TITLE
Syntax highlighting breaks in #[doc=""] blocks

### ISSUE THREAD

**Issue by shailesh1729** [jhasse/sublime-rust#24]
See the snippet below.  This snippet is a documentation block in a Rust source file which contains a code example. As such the sublime-rust parser isn't able to recognize the code example separately. This is manageable. But a bigger issue is: since there is a `]` present in the code block, the parser thinks that the `#doc` block has finished there itself.  This breaks the syntax highlighting completely for the rest of the file.  The solution I can think of at this moment is that `[doc="` should be matched with `"]` for closing the documentation block. Don't know how is it implemented internally.

~~~
#[doc="Returns a 64-bit signed integer matrix whose entries are
picked up from a slice in column wise order.
    let m = matrix_i32(2,2, [1,2,3,4]);
    for i in range(0, 4){
        let c = i >> 1;
        let r = i & 1;            
        assert_eq!(m.get(r, c), (i + 1) as i32);
    }
"]
~~~

**Comment by rprichard** [comment]
This issue also affects `#[rustc_on_unimplemented = "...]..."]`.  From libcore/fmt/mod.rs:
```rust
#[rustc_on_unimplemented = "`{Self}` cannot be formatted using `:?`; if it is \
                            defined in your crate, add `#[derive(Debug)]` or \
                            manually implement it"]
```
(The GitHub syntax coloring breaks on the code, too!)

**Comment by rprichard** [comment]
The highlighting actually works correctly as long as the string literal inside the attribute is recognized.  The problem is that it isn't recognized once it spans multiple lines.  When it isn't recognized, the `]` inside the literal terminates the attribute.

GitHub (currently) works the same way, e.g.:
```rust
#[doc="Test 1 2 3 ] 4 5 6" second]   fn main() {}
#[doc="Test 1 2 \
3 ] 4 5 6" second]   fn main() {}
```
I have what I *think* is a fix: move the main string literal patterns into the "repository", then inside of the `comment.block.attribute.rust` pattern, replace the existing `"\".+?\""` string literal pattern with a reference to the full patterns in the repository.
